---
title: "Final Project Graph"
author: "Brian Anderson"
output: 
  html_document:
    df_print: paged
    code_download: true
    theme: cerulean
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE, error=TRUE, message=FALSE, warning=FALSE)
```

```{r libraries}
library(tidyverse)     # for graphing and data cleaning
library(lubridate)     # for date manipulation
library(ggthemes)      # for even more plotting theme
library(gganimate)     # for adding animation layers to ggplots
library(transformr)    # for "tweening" (gganimate)
library(gifski)        # for creating the gif
library(shiny)         # for creating interactive apps
library(readr)
theme_set(theme_minimal()) # My favorite ggplot() theme :)
```

## Data choice 1: Video Game Sales

```{r}
vgsales <- read.csv("vgsales.csv")
view(vgsales)
```

### Tidy Tuesday Graph

```{r, fig.alt = Animated BAr Chart showin cumulative video game sales by genre from 1980-2020}
vgsales %>%
  group_by( Year,Genre) %>% 
  summarize(total_genre_sum = sum(Global_Sales)) %>% 
  ungroup() %>% 
  complete(Year,Genre) %>% 
  arrange(Genre,Year) %>% 
  group_by(Genre) %>% 
  replace_na(list(total_genre_sum = 0)) %>% 
  mutate(cum_genre_sum = cumsum(total_genre_sum)) %>%
  filter(cum_genre_sum > 0) %>% 
  filter(n()>=13) %>% 
  top_n(n = 12,wt = cum_genre_sum) %>% 
  arrange(Year,desc(cum_genre_sum)) %>% 
  mutate(rank = 1:n()) %>% 
  ggplot(aes(x = cum_genre_sum,
             y = factor(rank),
             fill = Genre,
             group = Genre)) +
  geom_col() +
  geom_text(aes(label = Genre),
            color = "white",
            hjust = "right") +
  labs(title = "Popular Video Game Genres based on Worldwide Sales",
       subtitle = "Year: {frame_time}",
       x = "", 
       y = "",
       caption = "Plot created by Brian Anderson, Data from Vgsales") + 
  transition_time(Year)

```

```{r}
vgsales %>%
  group_by( Year,Genre) %>% 
  summarize(total_NA_genre_sum = sum(NA_Sales), 
            total_EU_genre_sum = sum(EU_Sales), 
            total_JP_genre_sum = sum(JP_Sales),
            total_other_genre_sum = sum(Other_Sales)) %>% 
  ungroup() %>% 
  complete(Year,Genre) %>% 
  arrange(Genre,Year) %>% 
  group_by(Genre) %>% 
  replace_na(list(total_NA_genre_sum = 0, total_EU_genre_sum  = 0, total_JP_genre_sum  = 0, total_other_genre_sum = 0)) %>% 
  mutate(cum_NA_genre_sum = cumsum(total_NA_genre_sum), cum_EU_genre_sum = cumsum(total_EU_genre_sum),cum_JP_genre_sum = cumsum(total_JP_genre_sum),cum__other_genre_sum = cumsum(total_other_genre_sum)) %>%   ggplot(aes(x = cum_genre_sum,
             y = factor(rank),
             fill = Genre,
             group = Genre))+
  geom_
```




